In [99]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score

In [69]:
# load data
df = pd.read_csv('data/crx.data',sep=',', header=None)

df.columns = ['A' + str((i + 1)) for i in range(df.shape[1])]

# remove missing values
for i in df.columns:
    df = df.drop(index=df[df[i]=='?'].index, axis=0)

# shuffle
df = shuffle(df)

/Users/ranley/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

In [70]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [71]:
indices = ['A1', 'A4', 'A5', 'A6', 'A7', 'A9', 'A10', 'A12', 'A13']

for name in indices:
    one_hot = pd.get_dummies(X[name])
    names = []
    for col in one_hot.columns:
        names.append(name + '_' + col)
    # Drop column as it is now encoded
    X = X.drop(name,axis = 1)
    # Join the encoded df
    one_hot.columns = names
    X = X.join(one_hot)
X

,A2,A3,A8,A11,A14,A15,A1_a,A1_b,A4_l,A4_u,...,A7_z,A9_f,A9_t,A10_f,A10_t,A12_f,A12_t,A13_g,A13_p,A13_s
137,33.58,2.750,4.250,6,00204,0,0,1,0,1,...,0,0,1,0,1,1,0,1,0,0
140,31.25,3.750,0.625,9,00181,0,1,0,0,1,...,0,0,1,0,1,0,1,1,0,0
686,22.67,0.750,2.000,2,00200,394,1,0,0,1,...,0,1,0,0,1,0,1,1,0,0
313,18.58,10.000,0.415,0,00080,42,1,0,0,1,...,0,1,0,1,0,1,0,1,0,0
49,23.92,0.665,0.165,0,00100,0,0,1,0,1,...,0,1,0,1,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,20.83,8.500,0.165,0,00000,351,1,0,0,1,...,0,1,0,1,0,1,0,1,0,0
149,52.83,15.000,5.500,14,00000,2200,1,0,0,1,...,0,0,1,0,1,1,0,1,0,0
495,19.17,9.500,1.500,0,00120,2206,0,1,0,1,...,0,0,1,1,0,1,0,1,0,0
347,26.75,4.500,2.500,0,00200,1210,0,1,0,0,...,0,1,0,1,0,1,0,1,0,0
653,21.50,11.500,0.500,0,00100,68,0,1,0,1,...,0,0,1,1,0,0,1,1,0,0

In [79]:
# encoding y
y.loc[y == '+'] = 1
y.loc[y == '-'] = 0
y = y.astype('int')

/Users/ranley/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [80]:
y

137    1
140    1
686    0
313    0
49     1
      ..
646    0
149    1
495    1
347    0
653    0
Name: A16, Length: 653, dtype: int64

In [81]:
# train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [89]:
clf1 = LogisticRegression(penalty='none')
clf1.fit(X_train,y_train)

/Users/ranley/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(penalty='none')

In [96]:
y_pred = clf1.predict(X_test)

0.875

In [100]:
# evaluate
print('accuracy: ' + str(accuracy_score(y_test, y_pred)))
print('balanced accuracy: ' + str(balanced_accuracy_score(y_test, y_pred)))

accuracy: 0.875
balanced accuracy: 0.8745082612116444